spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    #    filters: stat,wall

    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filters: wall
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          enabled: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
      aop-patterns: com.mld.springboot10datasource.*


  jdbc:
    template:
      query-timeout: 3
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    #    默认使用Lettuce客户端，如果想使用Jedis则需 引入jedis依赖并要配置client-type
    client-type: jedis
  boot:
    admin:
      client:
        url: http://localhost:8888
        instance:
          prefer-ip: true

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印SQL



management:
  endpoints:
    enabled-by-default: true #默认开启所有端点 true
    web:  #以web方式暴露端点
      exposure:
        include: '*' #暴露所有端点
  endpoint:
    health:
      show-details: always
      enabled: true
    metrics:
      enabled: true
    beans:
      enabled: true
    info:
      enabled: true


#    web:
#      exposure:
#        include: '*'
info:
  appName: springBoot10
  myProp: kkkk
  mavenMess: @project.artifactId@  #获取pom文件中的信息
