spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#    filters: stat,wall

    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filters: wall
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          enabled: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
      aop-patterns: com.mld.springboot10datasource.*


  jdbc:
    template:
      query-timeout: 3
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
#    默认使用Lettuce客户端，如果想使用Jedis则需 引入jedis依赖并要配置client-type
    client-type: jedis

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true


